export default
[
  "Accounting & Finance",
  "Artificial Intelligence",
  "Art & Design",
  "Biological Sciences",
  "Business & Management Studies",
  "C",
  "Computer Networks",
  "Chemistry",
  "Economics",
  "English",
  "Fashion",
  "Film Making",
  "Food Science",
  "Forensic Science",
  "Marketing",
  "Mathematics",
  "Music",
  "Python",
  "Programming in Java",
  "Political Science",
  "Social Policy",
  "Sociology",
  "Sports Science",
  "Youth Work"
];
